---
language: python
services: docker

env:
  global:
    - ROLE_NAMESPACE: inverse-inc
    - ROLE_NAME: gitlab-buildpkg-tools
  matrix:
    # Test PPA
    - MOLECULE_DISTRO=debian9
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools
      DEB_PACKAGES_NAME="['apt-add-gitlab','gitlab-buildpkg-tools']"

    - MOLECULE_DISTRO=debian10
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools
      DEB_PACKAGES_NAME="['apt-add-gitlab','gitlab-buildpkg-tools']"

    - MOLECULE_DISTRO=centos7
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools
      RPM_PACKAGES_NAME="['yum-add-gitlab','gitlab-buildpkg-tools']"

    # - MOLECULE_DISTRO=centos8
    #   CI_PROJECT_NAME=gitlab-buildpkg-tools
    #   CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools
    #   RPM_PACKAGES_NAME="['yum-add-gitlab','gitlab-buildpkg-tools']"

    # Test additional
    - MOLECULE_DISTRO=debian9
      MOLECULE_PLAYBOOK=playbook-additional.yml

    - MOLECULE_DISTRO=debian10
      MOLECULE_PLAYBOOK=playbook-additional.yml

    - MOLECULE_DISTRO=centos7
      MOLECULE_PLAYBOOK=playbook-additional.yml

    # - MOLECULE_DISTRO=centos8
    #   MOLECULE_PLAYBOOK=playbook-additional.yml

    # Test enable disable repos (only for EL because that didn't make sense
    # for Debian)
    - MOLECULE_DISTRO=centos7
      MOLECULE_PLAYBOOK=playbook-enable-disable-repos.yml

    # - MOLECULE_DISTRO=centos8
    #   MOLECULE_PLAYBOOK=playbook-enable-disable-repos.yml

    # Test PPA and additional
    - MOLECULE_DISTRO=debian9
      MOLECULE_PLAYBOOK=playbook-ppa-and-additional.yml
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools

    - MOLECULE_DISTRO=debian10
      MOLECULE_PLAYBOOK=playbook-ppa-and-additional.yml
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools

    - MOLECULE_DISTRO=centos7
      MOLECULE_PLAYBOOK=playbook-ppa-and-additional.yml
      CI_PROJECT_NAME=gitlab-buildpkg-tools
      CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools

    # - MOLECULE_DISTRO=centos8
    #   MOLECULE_PLAYBOOK=playbook-ppa-and-additional.yml
    #   CI_PROJECT_NAME=gitlab-buildpkg-tools
    #   CI_PAGES_URL=http://orange-opensource.gitlab.io/gitlab-buildpkg-tools

    # Test priority (only for EL because that didn't make sense
    # for Debian)
    - MOLECULE_DISTRO=centos7
      MOLECULE_PLAYBOOK=playbook-priority.yml

install:
  # Install test dependencies.
  - pip3 install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAMESPACE.$ROLE_NAME
  - cd $ROLE_NAMESPACE.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
