---
- name: install dependencies to install packages from repos
  apt:
    name: "{{ gitlab_buildpkg_tools__deb_deps_pkgs }}"
    state: "{{ gitlab_buildpkg_tools__deb_deps_pkgs_state }}"
    update_cache: yes

- name: add public keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: '{{ gitlab_buildpkg_tools__deb_combined_keys }}'

- name: install repos
  template:
    src: sources.list.j2
    dest: "{{ gitlab_buildpkg_tools__deb_sources_dir }}/{{ item['name'] }}.list"
  loop: "{{ gitlab_buildpkg_tools__deb_combined_repos }}"
  loop_control:
    label: "{{ item['name'] }}"

# update_cache to take new key(s) and repo(s) into account
- name: install packages from Debian repos
  apt:
    name: "{{ gitlab_buildpkg_tools__deb_pkgs }}"
    update_cache: yes
    state: "{{ gitlab_buildpkg_tools__deb_pkgs_state }}"
