---
- name: install dependencies to install packages from repo
  yum:
    name: "{{ gitlab_buildpkg_tools__rpm_pkgs }}"
    state: latest

- name: add public key
  rpm_key: 
    state: present
    key: "{{ gitlab_buildpkg_tools__ci_pages_gpgkey_url }}"

- name: install {{ gitlab_buildpkg_tools__ci_project_name }} repo from gitlab pages
  yum_repository:
    name: "{{ gitlab_buildpkg_tools__ci_project_name }}"
    description: "{{ gitlab_buildpkg_tools__ci_project_name }} repo"
    baseurl: "{{ gitlab_buildpkg_tools__ci_pages_url }}/centos/$releasever/$basearch"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ gitlab_buildpkg_tools__ci_pages_gpgkey_url }}"
    metadata_expire: "900"
    skip_if_unavailable: no
    repo_gpgcheck: no

- name: install package from repo
  yum:
    name: "{{ gitlab_buildpkg_tools__ci_built_pkg }}"
    update_cache: yes
    state: latest
