---
- name: install dependencies to install packages from repos
  yum:
    name: "{{ gitlab_buildpkg_tools__rpm_deps_pkgs }}"
    state: present

- name: add public keys
  rpm_key:
    key: "{{ item }}"
    state: present
  loop: "{{ gitlab_buildpkg_tools__rpm_combined_keys }}"

- name: install repos
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['name'] }} repo"
    baseurl: "{{ item['baseurl'] }}"
    enabled: yes
    gpgcheck: yes
    metadata_expire: "900"
    skip_if_unavailable: no
    repo_gpgcheck: no
  loop: "{{ gitlab_buildpkg_tools__rpm_combined_repos }}"
  loop_control:
    label: "{{ item['name'] }}"

# update_cache to take new key(s) and repo(s) into account
- name: install packages from RPM repos
  yum:
    name: "{{ gitlab_buildpkg_tools__rpm_pkgs }}"
    update_cache: yes
    state: present
