---
- name: install dependencies to install packages from repos
  yum:
    name: "{{ gitlab_buildpkg_tools__rpm_deps_pkgs }}"
    state: present

- name: add public keys
  rpm_key: 
    key: "{{ item['gpgkey_url'] }}"
    state: present
  loop: "{{ gitlab_buildpkg_tools__rpm_combined_repos }}"
  loop_control:
    label: "{{ item['gpgkey_url'] }}"

- name: install repos
  yum_repository:
    name: "{{ item['name'] }}"
    description: "{{ item['name'] }} repo"
    baseurl: "{{ item['baseurl'] }}/centos/$releasever/{{ item['extra_path'] | d() }}/$basearch"
    enabled: yes
    gpgcheck: yes
    metadata_expire: "900"
    skip_if_unavailable: no
    repo_gpgcheck: no
  loop: "{{ gitlab_buildpkg_tools__rpm_combined_repos }}"
  loop_control:
    label: "{{ item['name'] }}"

# latest to ensure we always install latest builds
- name: install packages from RPM repos
  yum:
    name: "{{ gitlab_buildpkg_tools__rpm_built_pkg }}"
    update_cache: yes
    state: latest
