---
dependency:
  name: galaxy
  
driver:
  name: docker
  
lint:
  name: yamllint
  
platforms:
  - name: instance
    # allow to override docker image with env var
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  # allow to override playbook use for converge action with env var
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
    
verifier:
  name: testinfra
  lint:
    name: flake8

scenario:
  name: default  # optional
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
