---
dependency:
  name: galaxy
  
driver:
  name: docker
  
lint:
  name: yamllint
  
platforms:
  - name: instance
    # allow to override docker image with env var
    image: "${MOLECULE_DISTRO:-centos}:${MOLECULE_IMAGE_TAG:-7}"
    
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  # allow to override playbook use for converge action with env var
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}

verifier:
  name: testinfra
  lint:
    name: flake8

scenario:
  name: default  # optional
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
