---
- name: Converge
  hosts: all
  become: True

  vars:
    gitlab_buildpkg_tools__rpm_keys:
      - 'https://inverse.ca/downloads/GPG_PUBLIC_KEY'

    gitlab_buildpkg_tools__rpm_deps_repos:
      - name: perl-client
        baseurl: https://inverse-inc.gitlab.io/perl-client/centos/$releasever/$basearch
        priority: 1
      - name: packetfence
        baseurl: http://inverse.ca/downloads/PacketFence/centos/$releasever/11.0/$basearch
        priority: 99

    gitlab_buildpkg_tools__rpm_pkgs:
      - fingerbank

  roles:
    - role: inverse-inc.gitlab-buildpkg-tools
